# Quarkus will choose application.yaml over application.properties.
quarkus:
    http:
        port: 8081

    # Logging
    log:
        level: INFO
        category:
            "org.commonjava.util.gateway":
                level: DEBUG

# Proxy services
proxy:
    services:
        - "host: localhost, port: 8080, methods: POST/PUT, path-pattern: .+"
        - "host: indy-infra-nos-automation.cloud.paas.psi.redhat.com, port: 80, methods: GET/HEAD, path-pattern: .+"
